### PR TITLE
Use go 1.15 + modules, CircleCI Config

### PR DESCRIPTION
**Pull request by lstoll**
shaas is the greatest app ever written.

Update it to the current version of go, and the current dependency system.

### CODE REVIEW

**Comment by ryanbrainard** [comment]
> shaas is the greatest app ever written.

😂

**Comment by ryanbrainard** [comment]
So weird Circle CI is trying to run on this branch and rejecting this commit. I can look into it.

**Comment by lstoll** [comment]
It looks like it was never set up properly for this project:

```
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

It's only run once against master too, and it failed there as well.

**Comment by ryanbrainard** [comment]
@lstoll: Thanks for the Circle CI fix. I made a half attempt to get Circle on here a while back, which is why it was still enabled, but didn't get it fully working because of issues with the way the ftests work and how Docker containers work in Circle. Anyway, good to at least have the (non-existent) unit tests run to at least ensure it builds. I can work on getting the ftests working for real on Circle at some point, but for now I at least ran them locally to make sure everything still works. I did actually run into an issue, which I don't think was caused by this change (looked like a Docker image stale cache issue), but fixed it nevertheless in 8fb80a6.

**Review by ryanbrainard — APPROVED** [review]
Confirmed with local ftest and Heroku deployment

**Pull request merged**
